name: Download, repack and release go2rtc

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 */3 * * *'

jobs:
  build:
    name: Download go2rtc and create a .zip release
    runs-on: ubuntu-latest
    steps:
      - id: get-go2rtc-version
        name: Get latest go2rtc version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: AlexxIT
          repo: go2rtc
      - id: download-go2rtc
        name: Download latest go2rtc version
        run: |
          curl -L -o go2rtc_linux_amd64 https://github.com/AlexxIT/go2rtc/releases/download/${{ steps.get-go2rtc-version.outputs.release }}/go2rtc_linux_amd64
          curl -L -o go2rtc_linux_arm https://github.com/AlexxIT/go2rtc/releases/download/${{ steps.get-go2rtc-version.outputs.release }}/go2rtc_linux_arm
          curl -L -o go2rtc_linux_arm64 https://github.com/AlexxIT/go2rtc/releases/download/${{ steps.get-go2rtc-version.outputs.release }}/go2rtc_linux_arm64
          curl -L -o go2rtc_linux_armv6 https://github.com/AlexxIT/go2rtc/releases/download/${{ steps.get-go2rtc-version.outputs.release }}/go2rtc_linux_armv6
      - id: create-release-info
        name: Create release-info.json file
        run: |
          echo -e "{\"project_name\": \"go2rtc (via go2moon)\",\"project_owner\": \"AlexxIT / jeikobu__\",\"version\":\"${{ steps.get-go2rtc-version.outputs.release }}\"}" > release-info.json
      - id: create-release-zip
        name: Create release zip file
        uses: vimtor/action-zip@v1.2
        with:
          files: go2rtc_linux_amd64 go2rtc_linux_arm go2rtc_linux_arm64 go2rtc_linux_armv6 release-info.json
          dest: go2rtc.zip
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-go2rtc-version.outputs.release }}
          release_name: Release ${{ steps.get-go2rtc-version.outputs.release }}
          body: ${{ steps.get-go2rtc-version.outputs.description }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: comnoco/upload-release-asset-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./go2rtc.zip
          asset_name: go2rtc.zip
          asset_content_type: application/zip

